# Generated by Django 5.0.3 on 2024-11-16 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancerecord",
            options={
                "verbose_name": "Attendance Record",
                "verbose_name_plural": "Attendance Records",
            },
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="entrance_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="exit_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendancerecord",
            name="exit_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 11, 16, 18, 12, 25, 758677)
            ),
        ),
    ]
