# Generated by Django 5.0.3 on 2024-11-17 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0002_alter_attendancerecord_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="advance_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 11, 17, 17, 7, 3, 804632)
            ),
        ),
    ]
