# Generated by Django 5.0.3 on 2024-12-01 18:56

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0004_alter_attendancerecord_date_documentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrequest",
            name="club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hr.club",
            ),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 1, 18, 56, 17, 231215)
            ),
        ),
    ]
