# Generated by Django 5.0.3 on 2024-12-01 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0005_documentrequest_club_alter_attendancerecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 1, 19, 34, 23, 594531)
            ),
        ),
    ]
