# Generated by Django 5.0.3 on 2024-12-01 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0009_alter_attendancerecord_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2024, 12, 1, 20, 48, 52, 864091)
            ),
        ),
    ]
