# Generated by Django 5.0.3 on 2024-10-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
