# Generated by Django 5.0.3 on 2024-10-05 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clubs", "0002_alter_problem_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="is_solved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="problem",
            name="solved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problem",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
